create table car (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	make VARCHAR(50),
	model VARCHAR(50),
	price NUMERIC(10, 2)
);
insert into car (make, model, price) values ('Dodge', 'Colt', '72470.79');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '95996.38');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '98746.36');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '75930.62');
insert into car (make, model, price) values ('Toyota', 'Corolla', '79402.19');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '85204.50');
insert into car (make, model, price) values ('Audi', 'Q5', '95266.22');
insert into car (make, model, price) values ('Mazda', 'Mazda5', '74684.04');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '97984.98');
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', '89314.58');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '77145.61');
insert into car (make, model, price) values ('Mercury', 'Topaz', '95924.32');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '94428.28');
insert into car (make, model, price) values ('Infiniti', 'QX', '71183.91');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '81694.20');
insert into car (make, model, price) values ('Suzuki', 'Vitara', '55554.44');
insert into car (make, model, price) values ('Ford', 'Ranger', '81915.86');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '54703.90');
insert into car (make, model, price) values ('Plymouth', 'Laser', '57121.45');
insert into car (make, model, price) values ('Mazda', 'MX-5', '86123.39');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '78446.20');
insert into car (make, model, price) values ('BMW', '7 Series', '81436.41');
insert into car (make, model, price) values ('Saab', '900', '65927.82');
insert into car (make, model, price) values ('Porsche', '944', '53882.59');
insert into car (make, model, price) values ('Honda', 'Prelude', '77161.59');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '84263.48');
insert into car (make, model, price) values ('Land Rover', 'Range Rover Classic', '95870.53');
insert into car (make, model, price) values ('Ford', 'Windstar', '81845.89');
insert into car (make, model, price) values ('Hyundai', 'Tiburon', '69207.71');
insert into car (make, model, price) values ('Mercury', 'Cougar', '63678.37');
insert into car (make, model, price) values ('Mazda', 'RX-7', '64950.70');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '64976.60');
insert into car (make, model, price) values ('Mitsubishi', 'Endeavor', '59277.64');
insert into car (make, model, price) values ('Volkswagen', 'rio', '83183.05');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '52343.71');
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', '79333.76');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '53113.50');
insert into car (make, model, price) values ('Mazda', 'MX-6', '54172.45');
insert into car (make, model, price) values ('Volkswagen', 'Jetta III', '95725.03');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '68038.12');
insert into car (make, model, price) values ('Jaguar', 'S-Type', '92519.07');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '61269.75');
insert into car (make, model, price) values ('Buick', 'LeSabre', '55816.17');
insert into car (make, model, price) values ('Subaru', 'Leone', '67842.62');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '78861.12');
insert into car (make, model, price) values ('Mercury', 'Cougar', '93440.77');
insert into car (make, model, price) values ('Audi', 'A8', '71226.45');
insert into car (make, model, price) values ('Volvo', 'S80', '61334.21');
insert into car (make, model, price) values ('Volvo', 'C70', '60092.61');
insert into car (make, model, price) values ('Mitsubishi', 'Raider', '81366.53');
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', '56689.84');
insert into car (make, model, price) values ('Audi', 'Q5', '92143.49');
insert into car (make, model, price) values ('MINI', 'Countryman', '52633.64');
insert into car (make, model, price) values ('Honda', 'Civic', '64535.32');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '73922.89');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '75739.67');
insert into car (make, model, price) values ('Mercury', 'Mountaineer', '83802.14');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '65128.65');
insert into car (make, model, price) values ('Lexus', 'LFA', '82007.94');
insert into car (make, model, price) values ('Pontiac', '6000', '94823.89');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '78613.88');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '58302.91');
insert into car (make, model, price) values ('Dodge', 'Caliber', '62624.88');
insert into car (make, model, price) values ('Daewoo', 'Nubira', '73871.37');
insert into car (make, model, price) values ('Ford', 'E150', '63630.08');
insert into car (make, model, price) values ('Volvo', 'V50', '59112.56');
insert into car (make, model, price) values ('Buick', 'Skylark', '50809.74');
insert into car (make, model, price) values ('Suzuki', 'SX4', '50697.82');
insert into car (make, model, price) values ('Saab', '900', '57808.95');
insert into car (make, model, price) values ('Hyundai', 'Veracruz', '70985.38');
insert into car (make, model, price) values ('Toyota', '4Runner', '56132.97');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '93011.88');
insert into car (make, model, price) values ('Ford', 'Escort', '82884.99');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '72344.09');
insert into car (make, model, price) values ('GMC', 'Yukon XL', '78739.69');
insert into car (make, model, price) values ('Mazda', 'MX-5', '78428.80');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '52200.12');
insert into car (make, model, price) values ('Buick', 'Lucerne', '84794.96');
insert into car (make, model, price) values ('Ford', 'Escort', '96855.73');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '71907.19');
insert into car (make, model, price) values ('Volvo', 'XC90', '71971.75');
insert into car (make, model, price) values ('Chevrolet', '2500', '73424.54');
insert into car (make, model, price) values ('Subaru', 'Baja', '93971.14');
insert into car (make, model, price) values ('Toyota', 'Camry Solara', '96527.26');
insert into car (make, model, price) values ('Infiniti', 'QX', '56834.02');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '96950.41');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '95061.37');
insert into car (make, model, price) values ('Lincoln', 'Navigator', '74372.31');
insert into car (make, model, price) values ('Volkswagen', 'Touareg', '95836.65');
insert into car (make, model, price) values ('Oldsmobile', 'Toronado', '76082.19');
insert into car (make, model, price) values ('Ford', 'E-Series', '61396.27');
insert into car (make, model, price) values ('Morgan', 'Aero 8', '50686.74');
insert into car (make, model, price) values ('GMC', 'Envoy XL', '56478.28');
insert into car (make, model, price) values ('BMW', '5 Series', '77151.43');
insert into car (make, model, price) values ('Ford', 'F-Series Super Duty', '69540.70');
insert into car (make, model, price) values ('Ford', 'Escort', '92837.13');
insert into car (make, model, price) values ('Audi', 'Q5', '94031.61');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '72527.75');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '68841.00');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '83206.54');
insert into car (make, model, price) values ('Jeep', 'Liberty', '50326.87');
insert into car (make, model, price) values ('Hummer', 'H1', '79385.24');
insert into car (make, model, price) values ('Buick', 'Regal', '78160.94');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '97031.15');
insert into car (make, model, price) values ('Dodge', 'Magnum', '95191.47');
insert into car (make, model, price) values ('Ford', 'Laser', '75223.86');
insert into car (make, model, price) values ('Subaru', 'Baja', '74022.64');
insert into car (make, model, price) values ('Lexus', 'IS', '74686.33');
insert into car (make, model, price) values ('Hummer', 'H1', '59699.30');
insert into car (make, model, price) values ('Pontiac', 'G6', '53512.36');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '67133.87');
insert into car (make, model, price) values ('Honda', 'Fit', '78341.03');
insert into car (make, model, price) values ('Honda', 'Crosstour', '73070.72');
insert into car (make, model, price) values ('Daewoo', 'Leganza', '54001.52');
insert into car (make, model, price) values ('GMC', 'Yukon XL 1500', '60722.28');
insert into car (make, model, price) values ('MINI', 'MINI', '85704.86');
insert into car (make, model, price) values ('Lexus', 'ES', '95073.65');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '72033.34');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '60404.60');
insert into car (make, model, price) values ('Scion', 'xB', '54929.03');
insert into car (make, model, price) values ('BMW', 'Alpina B7', '56364.31');
insert into car (make, model, price) values ('Alfa Romeo', '164', '93687.42');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '62427.87');
insert into car (make, model, price) values ('Nissan', '200SX', '94272.40');
insert into car (make, model, price) values ('Mercedes-Benz', 'Sprinter', '93803.19');
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', '88451.66');
insert into car (make, model, price) values ('Jaguar', 'XK', '52990.54');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '77000.21');
insert into car (make, model, price) values ('Nissan', 'GT-R', '75669.93');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix Turbo', '76342.77');
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', '56378.86');
insert into car (make, model, price) values ('Honda', 'Element', '75880.37');
insert into car (make, model, price) values ('Chevrolet', 'Lumina', '94520.43');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '64452.26');
insert into car (make, model, price) values ('Ford', 'Mustang', '93086.37');
insert into car (make, model, price) values ('Honda', 'Pilot', '81151.32');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '52714.50');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '65864.23');
insert into car (make, model, price) values ('Mercury', 'Topaz', '74000.75');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '76653.20');
insert into car (make, model, price) values ('BMW', '750', '81527.51');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '80615.81');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', '56200.52');
insert into car (make, model, price) values ('Saturn', 'S-Series', '59489.87');
insert into car (make, model, price) values ('Hyundai', 'Accent', '76047.56');
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', '65974.52');
insert into car (make, model, price) values ('Studebaker', 'Avanti', '70945.07');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '79411.82');
insert into car (make, model, price) values ('Ford', 'E-Series', '78478.37');
insert into car (make, model, price) values ('Plymouth', 'Acclaim', '59882.58');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '91916.23');
insert into car (make, model, price) values ('Nissan', 'Xterra', '75211.93');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '89313.98');
insert into car (make, model, price) values ('Infiniti', 'QX56', '51688.53');
insert into car (make, model, price) values ('Ford', 'Club Wagon', '99082.09');
insert into car (make, model, price) values ('Honda', 'Civic', '83037.28');
insert into car (make, model, price) values ('Buick', 'Park Avenue', '70941.86');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '78276.11');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '90975.02');
insert into car (make, model, price) values ('GMC', 'Sonoma', '58586.67');
insert into car (make, model, price) values ('Ford', 'F350', '65958.50');
insert into car (make, model, price) values ('Land Rover', 'Discovery', '59248.91');
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed 3', '71963.46');
insert into car (make, model, price) values ('Honda', 'Civic', '83480.82');
insert into car (make, model, price) values ('Lexus', 'LS', '56767.91');
insert into car (make, model, price) values ('Pontiac', 'G6', '86023.07');
insert into car (make, model, price) values ('Porsche', 'Boxster', '87012.23');
insert into car (make, model, price) values ('Subaru', 'Loyale', '91273.94');
insert into car (make, model, price) values ('Ford', 'LTD Crown Victoria', '63939.12');
insert into car (make, model, price) values ('Ford', 'E250', '65206.83');
insert into car (make, model, price) values ('Mitsubishi', '3000GT', '78606.95');
insert into car (make, model, price) values ('Acura', 'RL', '99070.58');
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', '59577.57');
insert into car (make, model, price) values ('Toyota', 'Solara', '72832.65');
insert into car (make, model, price) values ('Jeep', 'Liberty', '68618.23');
insert into car (make, model, price) values ('Hummer', 'H2', '58319.67');
insert into car (make, model, price) values ('Chevrolet', 'Venture', '54028.61');
insert into car (make, model, price) values ('Acura', 'RL', '77925.56');
insert into car (make, model, price) values ('BMW', '3 Series', '86206.75');
insert into car (make, model, price) values ('Dodge', 'Stratus', '52060.59');
insert into car (make, model, price) values ('Mercedes-Benz', '400SEL', '88937.51');
insert into car (make, model, price) values ('Mazda', 'MX-6', '66596.75');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '66920.92');
insert into car (make, model, price) values ('Jaguar', 'XJ', '96422.29');
insert into car (make, model, price) values ('Mercury', 'Cougar', '92842.96');
insert into car (make, model, price) values ('GMC', 'Canyon', '83592.50');
insert into car (make, model, price) values ('Aston Martin', 'DBS', '82748.09');
insert into car (make, model, price) values ('Toyota', 'Matrix', '91913.87');
insert into car (make, model, price) values ('Ford', 'Fiesta', '71116.70');
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', '67414.89');
insert into car (make, model, price) values ('Mercury', 'Cougar', '90365.43');
insert into car (make, model, price) values ('Nissan', '240SX', '58075.78');
insert into car (make, model, price) values ('Volvo', 'S40', '89597.50');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '75717.14');
insert into car (make, model, price) values ('Lamborghini', 'Murciélago', '58662.95');
insert into car (make, model, price) values ('Toyota', 'Truck Xtracab SR5', '62600.10');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '83240.31');
insert into car (make, model, price) values ('Chrysler', 'Concorde', '80239.67');
insert into car (make, model, price) values ('Volvo', 'V40', '60716.48');
insert into car (make, model, price) values ('Mazda', 'MX-5', '81784.53');
insert into car (make, model, price) values ('Lexus', 'ES', '86423.70');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '51764.16');
insert into car (make, model, price) values ('Honda', 'CR-Z', '59018.72');
insert into car (make, model, price) values ('Aston Martin', 'DB9 Volante', '75014.19');
insert into car (make, model, price) values ('Dodge', 'Durango', '60654.32');
insert into car (make, model, price) values ('Bentley', 'Continental', '51899.68');
insert into car (make, model, price) values ('Chrysler', 'LHS', '76918.65');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '87451.64');
insert into car (make, model, price) values ('Chevrolet', 'Malibu Maxx', '85725.19');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL-Class', '84078.76');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '56949.78');
insert into car (make, model, price) values ('Chrysler', 'Town & Country', '77796.89');
insert into car (make, model, price) values ('Mazda', 'Mazda6', '95240.28');
insert into car (make, model, price) values ('Pontiac', 'Bonneville', '71223.96');
insert into car (make, model, price) values ('Chevrolet', 'Tracker', '66835.26');
insert into car (make, model, price) values ('Infiniti', 'Q', '78517.20');
insert into car (make, model, price) values ('BMW', '7 Series', '93842.17');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '84491.10');
insert into car (make, model, price) values ('Audi', '5000CS', '66223.82');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '83614.24');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '73741.83');
insert into car (make, model, price) values ('Eagle', 'Vision', '76491.90');
insert into car (make, model, price) values ('Ford', 'F350', '72104.29');
insert into car (make, model, price) values ('Lotus', 'Elan', '78302.78');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '97630.22');
insert into car (make, model, price) values ('Ford', 'Ranger', '99234.77');
insert into car (make, model, price) values ('Volvo', 'S60', '78733.15');
insert into car (make, model, price) values ('Bentley', 'Continental GTC', '53936.98');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '83830.75');
insert into car (make, model, price) values ('Buick', 'Regal', '88525.54');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '94363.75');
insert into car (make, model, price) values ('Jaguar', 'XK', '55045.77');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '99957.83');
insert into car (make, model, price) values ('Chevrolet', 'S10', '88123.22');
insert into car (make, model, price) values ('Porsche', 'Cayman', '61918.79');
insert into car (make, model, price) values ('Suzuki', 'XL-7', '54785.51');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '64159.69');
insert into car (make, model, price) values ('Volvo', '960', '59461.71');
insert into car (make, model, price) values ('Ford', 'F350', '96813.63');
insert into car (make, model, price) values ('Ford', 'F350', '62627.28');
insert into car (make, model, price) values ('Scion', 'tC', '95837.53');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '80272.25');
insert into car (make, model, price) values ('Toyota', 'Sequoia', '70039.44');
insert into car (make, model, price) values ('Kia', 'Sportage', '53764.87');
insert into car (make, model, price) values ('Toyota', 'Corolla', '86485.97');
insert into car (make, model, price) values ('Dodge', 'Avenger', '53361.57');
insert into car (make, model, price) values ('Volvo', '240', '93456.00');
insert into car (make, model, price) values ('Land Rover', 'LR2', '97413.04');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '74660.22');
insert into car (make, model, price) values ('Land Rover', 'Discovery', '52985.41');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '73534.09');
insert into car (make, model, price) values ('Ford', 'Escort', '93947.67');
insert into car (make, model, price) values ('Hyundai', 'Excel', '91238.20');
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', '90541.45');
insert into car (make, model, price) values ('BMW', 'X6 M', '72842.65');
insert into car (make, model, price) values ('Mitsubishi', 'Tredia', '99961.23');
insert into car (make, model, price) values ('GMC', 'Sierra 3500', '61661.78');
insert into car (make, model, price) values ('Buick', 'Riviera', '54940.76');
insert into car (make, model, price) values ('Mercedes-Benz', 'G55 AMG', '66609.90');
insert into car (make, model, price) values ('Mercury', 'Sable', '92479.00');
insert into car (make, model, price) values ('Mazda', 'MX-6', '92206.45');
insert into car (make, model, price) values ('BMW', 'Z4', '51713.09');
insert into car (make, model, price) values ('Dodge', 'Challenger', '85476.14');
insert into car (make, model, price) values ('BMW', '530', '71336.08');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '81686.22');
insert into car (make, model, price) values ('Dodge', 'Magnum', '69561.57');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '80914.35');
insert into car (make, model, price) values ('Acura', 'RSX', '56158.46');
insert into car (make, model, price) values ('Audi', 'S4', '76226.71');
insert into car (make, model, price) values ('Infiniti', 'I', '86288.66');
insert into car (make, model, price) values ('Aston Martin', 'V12 Vantage', '55839.17');
insert into car (make, model, price) values ('Oldsmobile', 'Cutlass', '64844.62');
insert into car (make, model, price) values ('Geo', 'Metro', '73031.42');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '51137.49');
insert into car (make, model, price) values ('Alfa Romeo', 'Spider', '58040.49');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '65089.08');
insert into car (make, model, price) values ('Nissan', 'Frontier', '89978.39');
insert into car (make, model, price) values ('Pontiac', 'Parisienne', '68894.88');
insert into car (make, model, price) values ('BMW', 'X3', '53379.37');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '77363.01');
insert into car (make, model, price) values ('Suzuki', 'X-90', '67590.59');
insert into car (make, model, price) values ('Buick', 'Roadmaster', '50691.61');
insert into car (make, model, price) values ('Mercury', 'Sable', '81128.44');
insert into car (make, model, price) values ('Ford', 'F-Series', '83933.42');
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage', '85067.22');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '95166.55');
insert into car (make, model, price) values ('Toyota', 'Yaris', '81212.88');
insert into car (make, model, price) values ('Porsche', '911', '88041.55');
insert into car (make, model, price) values ('Kia', 'Sedona', '86067.05');
insert into car (make, model, price) values ('Hyundai', 'Elantra', '78101.67');
insert into car (make, model, price) values ('Suzuki', 'XL-7', '95671.39');
insert into car (make, model, price) values ('Volkswagen', 'Corrado', '69234.16');
insert into car (make, model, price) values ('Toyota', 'MR2', '73581.09');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '72460.44');
insert into car (make, model, price) values ('Cadillac', 'Escalade EXT', '78971.76');
insert into car (make, model, price) values ('Buick', 'Electra', '82857.98');
insert into car (make, model, price) values ('Jeep', 'Commander', '56062.39');
insert into car (make, model, price) values ('Ford', 'LTD Crown Victoria', '76132.78');
insert into car (make, model, price) values ('Lotus', 'Exige', '61745.85');
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed6', '97495.47');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '67362.09');
insert into car (make, model, price) values ('GMC', '1500 Club Coupe', '87643.69');
insert into car (make, model, price) values ('MINI', 'Cooper', '90995.09');
insert into car (make, model, price) values ('Daewoo', 'Lanos', '80385.34');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '61465.83');
insert into car (make, model, price) values ('Hummer', 'H1', '66884.77');
insert into car (make, model, price) values ('Mazda', 'Protege', '92990.92');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '95564.30');
insert into car (make, model, price) values ('Isuzu', 'Ascender', '93657.93');
insert into car (make, model, price) values ('Lotus', 'Esprit', '73873.18');
insert into car (make, model, price) values ('GMC', 'Sierra 3500', '93991.81');
insert into car (make, model, price) values ('Oldsmobile', 'Aurora', '73887.28');
insert into car (make, model, price) values ('Mercedes-Benz', 'CL65 AMG', '74317.96');
insert into car (make, model, price) values ('Acura', 'MDX', '57168.88');
insert into car (make, model, price) values ('Mazda', 'Tribute', '87287.01');
insert into car (make, model, price) values ('Chevrolet', 'Venture', '80378.36');
insert into car (make, model, price) values ('Suzuki', 'Swift', '59098.40');
insert into car (make, model, price) values ('Ford', 'Escort ZX2', '63217.45');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '95891.26');
insert into car (make, model, price) values ('BMW', 'X6', '75852.06');
insert into car (make, model, price) values ('Lexus', 'LS', '93264.67');
insert into car (make, model, price) values ('Nissan', 'Altima', '95417.82');
insert into car (make, model, price) values ('Lexus', 'ES', '92575.03');
insert into car (make, model, price) values ('Acura', 'TL', '94193.28');
insert into car (make, model, price) values ('Audi', 'S4', '92401.04');
insert into car (make, model, price) values ('Jaguar', 'XJ', '91028.88');
insert into car (make, model, price) values ('Mazda', 'B-Series', '54608.73');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '85253.66');
insert into car (make, model, price) values ('Isuzu', 'Ascender', '90693.36');
insert into car (make, model, price) values ('GMC', 'Sierra Denali', '70586.75');
insert into car (make, model, price) values ('Subaru', 'Outback', '87881.91');
insert into car (make, model, price) values ('Ford', 'F-Series', '69890.22');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '52644.69');
insert into car (make, model, price) values ('Lotus', 'Esprit', '63028.23');
insert into car (make, model, price) values ('Mitsubishi', 'Expo', '63579.94');
insert into car (make, model, price) values ('Lexus', 'IS-F', '63558.13');
insert into car (make, model, price) values ('Subaru', 'Outback', '51366.52');
insert into car (make, model, price) values ('Hyundai', 'Veracruz', '92196.58');
insert into car (make, model, price) values ('Kia', 'Sephia', '98093.40');
insert into car (make, model, price) values ('Toyota', 'Corolla', '87367.22');
insert into car (make, model, price) values ('Toyota', 'Prius', '90915.65');
insert into car (make, model, price) values ('Chevrolet', '2500', '51705.72');
insert into car (make, model, price) values ('Mazda', 'MX-5', '84263.09');
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', '80713.79');
insert into car (make, model, price) values ('GMC', 'Sierra Hybrid', '57753.12');
insert into car (make, model, price) values ('Chevrolet', 'G-Series 2500', '50251.13');
insert into car (make, model, price) values ('Hyundai', 'Accent', '54933.36');
insert into car (make, model, price) values ('Ford', 'Mustang', '59180.96');
insert into car (make, model, price) values ('Volkswagen', 'Rabbit', '67400.95');
insert into car (make, model, price) values ('Dodge', 'Dakota', '89870.47');
insert into car (make, model, price) values ('MINI', 'Cooper Clubman', '61336.46');
insert into car (make, model, price) values ('Lexus', 'LX', '99365.55');
insert into car (make, model, price) values ('Mercedes-Benz', '500E', '75324.92');
insert into car (make, model, price) values ('Toyota', 'Camry', '73057.83');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '75544.88');
insert into car (make, model, price) values ('Toyota', 'Supra', '63519.48');
insert into car (make, model, price) values ('Mercedes-Benz', 'GL-Class', '54752.18');
insert into car (make, model, price) values ('Mitsubishi', 'Mirage', '61174.65');
insert into car (make, model, price) values ('Subaru', 'Alcyone SVX', '95947.23');
insert into car (make, model, price) values ('Mercury', 'Sable', '96107.56');
insert into car (make, model, price) values ('Bentley', 'Brooklands', '88946.38');
insert into car (make, model, price) values ('Chevrolet', 'TrailBlazer', '96407.98');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '72270.55');
insert into car (make, model, price) values ('Saab', '9-3', '93343.86');
insert into car (make, model, price) values ('Eagle', 'Summit', '64552.19');
insert into car (make, model, price) values ('Spyker', 'C8 Spyder Wide Body', '83730.36');
insert into car (make, model, price) values ('Spyker', 'C8', '84470.01');
insert into car (make, model, price) values ('Saturn', 'VUE', '58004.34');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '58370.53');
insert into car (make, model, price) values ('Nissan', 'Leaf', '51308.07');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '66950.87');
insert into car (make, model, price) values ('Isuzu', 'Oasis', '73885.88');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche', '83383.10');
insert into car (make, model, price) values ('Jaguar', 'XJ Series', '89704.66');
insert into car (make, model, price) values ('Subaru', 'Forester', '55398.49');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '86738.05');
insert into car (make, model, price) values ('Subaru', 'SVX', '90221.19');
insert into car (make, model, price) values ('GMC', 'Sonoma Club Coupe', '65623.44');
insert into car (make, model, price) values ('Ford', 'Aspire', '83548.09');
insert into car (make, model, price) values ('GMC', 'Savana', '58200.95');
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', '56230.19');
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B250', '72461.41');
insert into car (make, model, price) values ('Lexus', 'GS', '86116.21');
insert into car (make, model, price) values ('Mazda', 'Familia', '56973.80');
insert into car (make, model, price) values ('Mercury', 'Topaz', '73433.29');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '80120.77');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '85438.07');
insert into car (make, model, price) values ('BMW', 'X5', '55262.67');
insert into car (make, model, price) values ('Oldsmobile', 'Bravada', '65496.22');
insert into car (make, model, price) values ('MINI', 'Clubman', '80414.71');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '95852.56');
insert into car (make, model, price) values ('Pontiac', 'G5', '86286.52');
insert into car (make, model, price) values ('Mercury', 'Montego', '50889.55');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '92753.87');
insert into car (make, model, price) values ('Mitsubishi', 'Chariot', '76478.52');
insert into car (make, model, price) values ('Chevrolet', 'Cavalier', '61448.82');
insert into car (make, model, price) values ('GMC', 'Yukon XL 2500', '81326.38');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '90265.27');
insert into car (make, model, price) values ('Audi', '4000s Quattro', '76944.06');
insert into car (make, model, price) values ('Lotus', 'Esprit', '72369.25');
insert into car (make, model, price) values ('Oldsmobile', 'Silhouette', '93032.12');
insert into car (make, model, price) values ('Buick', 'Century', '92537.67');
insert into car (make, model, price) values ('Buick', 'LeSabre', '68229.73');
insert into car (make, model, price) values ('Dodge', 'Stealth', '92753.56');
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', '60737.02');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '78749.10');
insert into car (make, model, price) values ('Toyota', 'Camry Solara', '64245.97');
insert into car (make, model, price) values ('Isuzu', 'Stylus', '51884.04');
insert into car (make, model, price) values ('Honda', 'Odyssey', '81268.66');
insert into car (make, model, price) values ('Subaru', 'Tribeca', '53192.56');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '67843.62');
insert into car (make, model, price) values ('Chrysler', 'Pacifica', '75599.56');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '51387.78');
insert into car (make, model, price) values ('Ford', 'Taurus', '69496.47');
insert into car (make, model, price) values ('Subaru', 'Impreza', '95067.57');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '90978.02');
insert into car (make, model, price) values ('GMC', 'Yukon', '81925.82');
insert into car (make, model, price) values ('Audi', 'TT', '61981.46');
insert into car (make, model, price) values ('Mazda', '929', '92944.48');
insert into car (make, model, price) values ('BMW', 'M5', '64789.19');
insert into car (make, model, price) values ('Infiniti', 'G', '54807.39');
insert into car (make, model, price) values ('Eagle', 'Vision', '95974.39');
insert into car (make, model, price) values ('Cadillac', 'STS-V', '79556.08');
insert into car (make, model, price) values ('Dodge', 'Ram 2500', '84872.53');
insert into car (make, model, price) values ('Chevrolet', 'Sportvan G20', '86009.15');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '74912.19');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '94896.88');
insert into car (make, model, price) values ('Pontiac', 'Fiero', '67174.77');
insert into car (make, model, price) values ('Audi', 'Q5', '87737.29');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '51114.23');
insert into car (make, model, price) values ('Dodge', 'Ram Van 2500', '65164.73');
insert into car (make, model, price) values ('GMC', 'Sierra 3500', '75542.49');
insert into car (make, model, price) values ('Saab', '9-3', '58763.85');
insert into car (make, model, price) values ('GMC', '3500 Club Coupe', '51248.72');
insert into car (make, model, price) values ('GMC', 'Sierra 1500', '75303.38');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '85026.80');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '99502.25');
insert into car (make, model, price) values ('Maybach', 'Landaulet', '81627.78');
insert into car (make, model, price) values ('BMW', '530', '56538.44');
insert into car (make, model, price) values ('Toyota', 'Celica', '82501.93');
insert into car (make, model, price) values ('Aston Martin', 'DBS', '50549.61');
insert into car (make, model, price) values ('Mercury', 'Marauder', '51915.64');
insert into car (make, model, price) values ('Subaru', 'SVX', '51148.76');
insert into car (make, model, price) values ('Hyundai', 'Accent', '94514.35');
insert into car (make, model, price) values ('Ford', 'Festiva', '72438.76');
insert into car (make, model, price) values ('Ford', 'Mustang', '87336.76');
insert into car (make, model, price) values ('GMC', 'Vandura 3500', '82568.90');
insert into car (make, model, price) values ('Saturn', 'VUE', '69166.62');
insert into car (make, model, price) values ('Pontiac', 'GTO', '77314.28');
insert into car (make, model, price) values ('Acura', 'RL', '91792.65');
insert into car (make, model, price) values ('Chevrolet', 'APV', '61018.19');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '59853.56');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '62413.75');
insert into car (make, model, price) values ('Acura', 'NSX', '58267.52');
insert into car (make, model, price) values ('MINI', 'Cooper', '61497.18');
insert into car (make, model, price) values ('Panoz', 'Esperante', '84371.57');
insert into car (make, model, price) values ('Aston Martin', 'DBS', '84540.95');
insert into car (make, model, price) values ('Volkswagen', 'GLI', '83662.01');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '72679.36');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '79020.72');
insert into car (make, model, price) values ('Lexus', 'ES', '65846.13');
insert into car (make, model, price) values ('Maybach', '57', '51190.79');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '58149.85');
insert into car (make, model, price) values ('Honda', 'Accord', '71338.14');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '87566.38');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '95306.92');
insert into car (make, model, price) values ('Toyota', 'Yaris', '98359.99');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500', '95627.06');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '56011.07');
insert into car (make, model, price) values ('Ford', 'Econoline E350', '96532.15');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '55598.23');
insert into car (make, model, price) values ('Lexus', 'ES', '51697.74');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '52991.25');
insert into car (make, model, price) values ('Ford', 'Galaxie', '76309.82');
insert into car (make, model, price) values ('Porsche', '968', '57975.42');
insert into car (make, model, price) values ('Lexus', 'GS', '64178.43');
insert into car (make, model, price) values ('Studebaker', 'Avanti', '94208.54');
insert into car (make, model, price) values ('Mercury', 'Sable', '94022.09');
insert into car (make, model, price) values ('BMW', '5 Series', '70905.39');
insert into car (make, model, price) values ('Lincoln', 'MKX', '56447.77');
insert into car (make, model, price) values ('Dodge', 'D150 Club', '79796.61');
insert into car (make, model, price) values ('Dodge', 'Ram', '77371.52');
insert into car (make, model, price) values ('Saab', '9-3', '50025.70');
insert into car (make, model, price) values ('Mercedes-Benz', '300SE', '99982.48');
insert into car (make, model, price) values ('Dodge', 'Viper', '59912.16');
insert into car (make, model, price) values ('Ford', 'Focus', '70392.64');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '82526.32');
insert into car (make, model, price) values ('Audi', '5000CS Quattro', '90378.13');
insert into car (make, model, price) values ('Hummer', 'H1', '50160.70');
insert into car (make, model, price) values ('Toyota', 'Prius', '52286.09');
insert into car (make, model, price) values ('GMC', 'Suburban 1500', '57714.56');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '69384.43');
insert into car (make, model, price) values ('Aston Martin', 'Vantage', '73921.20');
insert into car (make, model, price) values ('Kia', 'Sedona', '51558.90');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '85223.10');
insert into car (make, model, price) values ('Nissan', 'Murano', '50684.22');
insert into car (make, model, price) values ('GMC', 'Savana 3500', '94085.00');
insert into car (make, model, price) values ('Citroën', 'CX', '83617.84');
insert into car (make, model, price) values ('Ford', 'Freestyle', '61102.15');
insert into car (make, model, price) values ('GMC', 'Yukon', '95109.09');
insert into car (make, model, price) values ('Porsche', '911', '76771.26');
insert into car (make, model, price) values ('BMW', '5 Series', '63441.15');
insert into car (make, model, price) values ('Mercury', 'Tracer', '53365.47');
insert into car (make, model, price) values ('Volkswagen', 'Eurovan', '62787.43');
insert into car (make, model, price) values ('Pontiac', 'Sunbird', '53386.91');
insert into car (make, model, price) values ('GMC', '1500', '50990.11');
insert into car (make, model, price) values ('BMW', '8 Series', '59183.86');
insert into car (make, model, price) values ('Kia', 'Sephia', '70224.77');
insert into car (make, model, price) values ('Dodge', 'Dakota', '72751.82');
insert into car (make, model, price) values ('Ford', 'Bronco', '58024.77');
insert into car (make, model, price) values ('GMC', 'Sonoma', '97273.89');
insert into car (make, model, price) values ('Honda', 'Accord', '57708.00');
insert into car (make, model, price) values ('Chrysler', 'Concorde', '77829.54');
insert into car (make, model, price) values ('GMC', 'Envoy', '50680.04');
insert into car (make, model, price) values ('Buick', 'Riviera', '98626.72');
insert into car (make, model, price) values ('Ford', 'Flex', '89726.48');
insert into car (make, model, price) values ('Ford', 'Windstar', '93301.05');
insert into car (make, model, price) values ('Buick', 'Lucerne', '64244.81');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLK-Class', '65502.76');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '51437.29');
insert into car (make, model, price) values ('Toyota', '4Runner', '82331.36');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '63658.84');
insert into car (make, model, price) values ('BMW', 'X3', '58921.49');
insert into car (make, model, price) values ('Dodge', 'Ram 1500', '76582.95');
insert into car (make, model, price) values ('Nissan', '240SX', '55647.75');
insert into car (make, model, price) values ('Audi', 'TT', '74034.95');
insert into car (make, model, price) values ('Aston Martin', 'V8 Vantage', '57272.28');
insert into car (make, model, price) values ('Pontiac', '6000', '86890.99');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '75740.07');
insert into car (make, model, price) values ('GMC', '2500', '86300.63');
insert into car (make, model, price) values ('Ford', 'GT', '98523.12');
insert into car (make, model, price) values ('Audi', 'A4', '79027.08');
insert into car (make, model, price) values ('Ford', 'Explorer', '78740.01');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer', '97026.39');
insert into car (make, model, price) values ('Ford', 'Crown Victoria', '76354.56');
insert into car (make, model, price) values ('Buick', 'Regal', '76061.69');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', '96936.21');
insert into car (make, model, price) values ('Lincoln', 'Town Car', '53306.73');
insert into car (make, model, price) values ('Nissan', '240SX', '92693.98');
insert into car (make, model, price) values ('Nissan', 'Maxima', '79928.16');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '94564.99');
insert into car (make, model, price) values ('Oldsmobile', 'Intrigue', '74080.51');
insert into car (make, model, price) values ('Land Rover', 'Discovery', '82170.89');
insert into car (make, model, price) values ('Saab', '9-5', '70269.73');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '76942.35');
insert into car (make, model, price) values ('Maybach', '57', '83932.24');
insert into car (make, model, price) values ('Ford', 'Taurus', '84336.35');
insert into car (make, model, price) values ('Audi', 'S8', '72230.00');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '87211.79');
insert into car (make, model, price) values ('Buick', 'Skylark', '54097.79');
insert into car (make, model, price) values ('Mercedes-Benz', 'G55 AMG', '87045.19');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '91684.16');
insert into car (make, model, price) values ('Mazda', '929', '62432.71');
insert into car (make, model, price) values ('Maybach', '57', '96803.49');
insert into car (make, model, price) values ('Mercedes-Benz', 'SLR McLaren', '89886.47');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '87299.04');
insert into car (make, model, price) values ('Ford', 'F350', '58587.14');
insert into car (make, model, price) values ('Subaru', 'Impreza WRX', '96680.38');
insert into car (make, model, price) values ('Toyota', 'Tacoma', '84528.85');
insert into car (make, model, price) values ('Lotus', 'Evora', '74699.87');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '96704.24');
insert into car (make, model, price) values ('Ford', 'F250', '79123.58');
insert into car (make, model, price) values ('Mercedes-Benz', 'SL-Class', '94745.04');
insert into car (make, model, price) values ('Nissan', 'Titan', '76084.28');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '93033.76');
insert into car (make, model, price) values ('BMW', 'Z8', '54771.22');
insert into car (make, model, price) values ('Ford', 'E350', '85199.62');
insert into car (make, model, price) values ('Toyota', 'T100', '76049.54');
insert into car (make, model, price) values ('BMW', '6 Series', '64331.01');
insert into car (make, model, price) values ('Toyota', 'Xtra', '85126.55');
insert into car (make, model, price) values ('Lincoln', 'Navigator L', '64292.67');
insert into car (make, model, price) values ('Acura', 'TL', '82184.64');
insert into car (make, model, price) values ('Ford', 'F150', '86739.14');
insert into car (make, model, price) values ('Lincoln', 'MKZ', '83071.12');
insert into car (make, model, price) values ('Volkswagen', 'Beetle', '78292.05');
insert into car (make, model, price) values ('Ford', 'Tempo', '55320.55');
insert into car (make, model, price) values ('Volvo', 'C30', '75890.51');
insert into car (make, model, price) values ('Lamborghini', 'Gallardo', '81972.60');
insert into car (make, model, price) values ('BMW', 'X6 M', '99261.38');
insert into car (make, model, price) values ('Isuzu', 'Ascender', '86104.42');
insert into car (make, model, price) values ('Mercedes-Benz', 'G-Class', '66443.16');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '84407.79');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 3500HD', '74665.28');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', '53500.58');
insert into car (make, model, price) values ('Isuzu', 'Hombre', '94213.24');
insert into car (make, model, price) values ('Mazda', 'RX-8', '88630.46');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '70873.45');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '59002.05');
insert into car (make, model, price) values ('Mitsubishi', 'Challenger', '85091.81');
insert into car (make, model, price) values ('Mazda', 'RX-7', '61868.16');
insert into car (make, model, price) values ('Dodge', 'Journey', '56965.89');
insert into car (make, model, price) values ('Chevrolet', 'Silverado Hybrid', '97890.19');
insert into car (make, model, price) values ('Mitsubishi', 'Truck', '79877.90');
insert into car (make, model, price) values ('Dodge', 'Ram 1500 Club', '81714.14');
insert into car (make, model, price) values ('Ford', 'Bronco', '98908.92');
insert into car (make, model, price) values ('Chevrolet', 'Cruze', '77095.96');
insert into car (make, model, price) values ('Infiniti', 'QX56', '87119.28');
insert into car (make, model, price) values ('Toyota', 'Celica', '55248.67');
insert into car (make, model, price) values ('Saab', '900', '91059.49');
insert into car (make, model, price) values ('Ford', 'Probe', '79893.63');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '62652.86');
insert into car (make, model, price) values ('Suzuki', 'Grand Vitara', '65893.13');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '62419.84');
insert into car (make, model, price) values ('Dodge', 'Aries', '78116.30');
insert into car (make, model, price) values ('Scion', 'xB', '74816.38');
insert into car (make, model, price) values ('Oldsmobile', 'Intrigue', '69203.78');
insert into car (make, model, price) values ('Buick', 'LaCrosse', '94926.59');
insert into car (make, model, price) values ('Cadillac', 'Fleetwood', '77989.89');
insert into car (make, model, price) values ('GMC', 'Yukon', '61031.67');
insert into car (make, model, price) values ('Maserati', 'Spyder', '90794.35');
insert into car (make, model, price) values ('MINI', 'Cooper', '96727.92');
insert into car (make, model, price) values ('Chrysler', 'Fifth Ave', '90166.31');
insert into car (make, model, price) values ('Ford', 'Focus', '65803.30');
insert into car (make, model, price) values ('Lamborghini', 'Diablo', '61935.98');
insert into car (make, model, price) values ('Dodge', 'Caravan', '80862.15');
insert into car (make, model, price) values ('Ford', 'F-Series', '73076.46');
insert into car (make, model, price) values ('Mitsubishi', 'Expo', '85838.74');
insert into car (make, model, price) values ('BMW', '3 Series', '71292.28');
insert into car (make, model, price) values ('Kia', 'Soul', '65829.74');
insert into car (make, model, price) values ('Aston Martin', 'Virage', '90534.04');
insert into car (make, model, price) values ('Mercedes-Benz', 'M-Class', '72234.02');
insert into car (make, model, price) values ('Volkswagen', 'GLI', '95049.54');
insert into car (make, model, price) values ('Buick', 'Riviera', '76810.18');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '96857.36');
insert into car (make, model, price) values ('Toyota', 'FJ Cruiser', '86028.22');
insert into car (make, model, price) values ('Volkswagen', 'Tiguan', '95626.68');
insert into car (make, model, price) values ('Scion', 'tC', '66556.58');
insert into car (make, model, price) values ('GMC', '1500 Club Coupe', '57632.81');
insert into car (make, model, price) values ('Saab', '9-3', '83299.02');
insert into car (make, model, price) values ('Kia', 'Sportage', '68007.74');
insert into car (make, model, price) values ('Hummer', 'H3', '54881.12');
insert into car (make, model, price) values ('Lexus', 'SC', '96014.42');
insert into car (make, model, price) values ('Buick', 'Lucerne', '57096.30');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '94238.09');
insert into car (make, model, price) values ('Cadillac', 'DeVille', '81509.33');
insert into car (make, model, price) values ('Porsche', 'Cayman', '81729.86');
insert into car (make, model, price) values ('BMW', '3 Series', '76487.63');
insert into car (make, model, price) values ('Chevrolet', '2500', '91755.56');
insert into car (make, model, price) values ('BMW', '745', '79178.90');
insert into car (make, model, price) values ('Honda', 'Accord', '98260.03');
insert into car (make, model, price) values ('Lexus', 'LX', '66747.70');
insert into car (make, model, price) values ('Audi', 'Allroad', '73208.88');
insert into car (make, model, price) values ('Suzuki', 'Swift', '60969.08');
insert into car (make, model, price) values ('GMC', 'Sierra 3500', '70530.43');
insert into car (make, model, price) values ('Porsche', 'Cayenne', '95071.21');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '73303.08');
insert into car (make, model, price) values ('Mazda', '626', '68394.71');
insert into car (make, model, price) values ('GMC', 'Sonoma Club Coupe', '57975.54');
insert into car (make, model, price) values ('Lexus', 'ES', '67509.09');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '84134.84');
insert into car (make, model, price) values ('Volkswagen', 'Fox', '79407.28');
insert into car (make, model, price) values ('Audi', 'A6', '74882.84');
insert into car (make, model, price) values ('Hyundai', 'Accent', '84078.11');
insert into car (make, model, price) values ('Lexus', 'ES', '54413.45');
insert into car (make, model, price) values ('Dodge', 'Ram 3500', '56224.75');
insert into car (make, model, price) values ('Scion', 'tC', '95553.46');
insert into car (make, model, price) values ('Isuzu', 'Axiom', '75286.04');
insert into car (make, model, price) values ('Mercury', 'Cougar', '87376.88');
insert into car (make, model, price) values ('Mazda', 'RX-7', '84630.77');
insert into car (make, model, price) values ('Mercury', 'Cougar', '67300.52');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '91534.88');
insert into car (make, model, price) values ('Mazda', 'CX-9', '50628.08');
insert into car (make, model, price) values ('GMC', '1500', '59973.63');
insert into car (make, model, price) values ('Mazda', '626', '66119.59');
insert into car (make, model, price) values ('Dodge', 'Nitro', '61651.20');
insert into car (make, model, price) values ('Acura', 'TL', '75189.77');
insert into car (make, model, price) values ('Infiniti', 'G37', '89682.50');
insert into car (make, model, price) values ('Saturn', 'S-Series', '81103.81');
insert into car (make, model, price) values ('Nissan', '370Z', '55983.71');
insert into car (make, model, price) values ('Hyundai', 'Santa Fe', '93705.97');
insert into car (make, model, price) values ('Volkswagen', 'Eurovan', '79682.63');
insert into car (make, model, price) values ('Mitsubishi', '3000GT', '78310.99');
insert into car (make, model, price) values ('Oldsmobile', 'Achieva', '67260.93');
insert into car (make, model, price) values ('GMC', 'Savana 2500', '73107.69');
insert into car (make, model, price) values ('Acura', 'TL', '54203.43');
insert into car (make, model, price) values ('Ford', 'F250', '98592.89');
insert into car (make, model, price) values ('Buick', 'Enclave', '52768.68');
insert into car (make, model, price) values ('Mazda', 'B-Series', '79499.45');
insert into car (make, model, price) values ('Ford', 'F-Series', '96984.00');
insert into car (make, model, price) values ('Kia', 'Amanti', '77045.25');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '81108.63');
insert into car (make, model, price) values ('Cadillac', 'DTS', '91825.10');
insert into car (make, model, price) values ('Infiniti', 'G', '64784.94');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '81173.21');
insert into car (make, model, price) values ('Infiniti', 'J', '55107.79');
insert into car (make, model, price) values ('Cadillac', 'Seville', '78078.70');
insert into car (make, model, price) values ('Ford', 'Explorer Sport Trac', '93818.29');
insert into car (make, model, price) values ('Toyota', 'RAV4', '67043.08');
insert into car (make, model, price) values ('Kia', 'Soul', '76831.92');
insert into car (make, model, price) values ('Isuzu', 'Space', '89663.96');
insert into car (make, model, price) values ('Mitsubishi', 'Starion', '93263.58');
insert into car (make, model, price) values ('Toyota', 'Camry', '64932.72');
insert into car (make, model, price) values ('Audi', 'riolet', '98608.96');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '59901.42');
insert into car (make, model, price) values ('Saab', '9-5', '77623.20');
insert into car (make, model, price) values ('Acura', 'RDX', '81690.94');
insert into car (make, model, price) values ('Mazda', '626', '71772.10');
insert into car (make, model, price) values ('Acura', 'ZDX', '63168.16');
insert into car (make, model, price) values ('Lexus', 'GS', '67218.59');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '97002.45');
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', '94125.23');
insert into car (make, model, price) values ('Toyota', 'TundraMax', '50855.72');
insert into car (make, model, price) values ('Lexus', 'RX', '52281.04');
insert into car (make, model, price) values ('Mercedes-Benz', 'W201', '86905.88');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', '78640.42');
insert into car (make, model, price) values ('Mitsubishi', 'Diamante', '91327.89');
insert into car (make, model, price) values ('Mazda', 'RX-7', '92087.49');
insert into car (make, model, price) values ('Dodge', 'Viper', '81651.27');
insert into car (make, model, price) values ('Mitsubishi', 'Mighty Max', '67243.61');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '74016.55');
insert into car (make, model, price) values ('Toyota', 'Avalon', '76294.91');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '55336.49');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '87697.22');
insert into car (make, model, price) values ('Jeep', 'Liberty', '93322.25');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '73796.65');
insert into car (make, model, price) values ('Lotus', 'Elan', '85259.62');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '52152.41');
insert into car (make, model, price) values ('BMW', '5 Series', '96561.85');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '75648.00');
insert into car (make, model, price) values ('Buick', 'Skylark', '78291.39');
insert into car (make, model, price) values ('Suzuki', 'Esteem', '65994.74');
insert into car (make, model, price) values ('Aptera', 'Typ-1', '73402.90');
insert into car (make, model, price) values ('Maybach', '57', '50913.18');
insert into car (make, model, price) values ('Pontiac', 'GTO', '96322.67');
insert into car (make, model, price) values ('Oldsmobile', 'Intrigue', '95084.16');
insert into car (make, model, price) values ('Ford', 'Econoline E350', '59530.46');
insert into car (make, model, price) values ('Ford', 'Focus', '50916.38');
insert into car (make, model, price) values ('Chevrolet', 'Camaro', '91248.38');
insert into car (make, model, price) values ('Mercedes-Benz', 'E-Class', '54893.83');
insert into car (make, model, price) values ('Lexus', 'LX', '94502.35');
insert into car (make, model, price) values ('Toyota', '4Runner', '58699.64');
insert into car (make, model, price) values ('Ford', 'Bronco', '63473.67');
insert into car (make, model, price) values ('Jeep', 'Grand Cherokee', '86468.87');
insert into car (make, model, price) values ('Chrysler', '300M', '61396.53');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '57585.37');
insert into car (make, model, price) values ('Isuzu', 'Oasis', '64972.43');
insert into car (make, model, price) values ('Toyota', 'Highlander', '73815.14');
insert into car (make, model, price) values ('Honda', 'Prelude', '71522.06');
insert into car (make, model, price) values ('Ford', 'Festiva', '78747.83');
insert into car (make, model, price) values ('Chevrolet', 'TrailBlazer', '70135.60');
insert into car (make, model, price) values ('Mercury', 'Mountaineer', '61832.13');
insert into car (make, model, price) values ('Audi', '90', '81573.60');
insert into car (make, model, price) values ('Mercury', 'Topaz', '66361.42');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '64259.14');
insert into car (make, model, price) values ('Ford', 'F-Series', '99317.60');
insert into car (make, model, price) values ('Pontiac', 'Parisienne', '96525.07');
insert into car (make, model, price) values ('Dodge', 'Dakota', '51853.55');
insert into car (make, model, price) values ('Pontiac', 'Sunfire', '83807.53');
insert into car (make, model, price) values ('Lamborghini', 'Countach', '63607.63');
insert into car (make, model, price) values ('Buick', 'Riviera', '57491.44');
insert into car (make, model, price) values ('Volkswagen', 'GTI', '92862.45');
insert into car (make, model, price) values ('Volkswagen', 'Jetta', '93937.97');
insert into car (make, model, price) values ('Hummer', 'H1', '91705.30');
insert into car (make, model, price) values ('Nissan', 'Pathfinder', '99685.56');
insert into car (make, model, price) values ('Cadillac', 'CTS-V', '55027.19');
insert into car (make, model, price) values ('Mitsubishi', 'Montero', '63511.83');
insert into car (make, model, price) values ('Ford', 'Escort', '66708.13');
insert into car (make, model, price) values ('Porsche', '911', '56973.36');
insert into car (make, model, price) values ('Dodge', 'Viper', '96687.46');
insert into car (make, model, price) values ('Hyundai', 'Genesis Coupe', '92973.11');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '95345.13');
insert into car (make, model, price) values ('Cadillac', 'STS', '90630.96');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '77540.36');
insert into car (make, model, price) values ('Ford', 'Econoline E250', '70197.23');
insert into car (make, model, price) values ('Isuzu', 'Trooper', '99998.21');
insert into car (make, model, price) values ('Mitsubishi', 'Montero', '61637.59');
insert into car (make, model, price) values ('Scion', 'xA', '56205.61');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', '73810.75');
insert into car (make, model, price) values ('Chrysler', 'Voyager', '89355.23');
insert into car (make, model, price) values ('Pontiac', 'Firefly', '53339.17');
insert into car (make, model, price) values ('Lexus', 'ES', '79162.99');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '64574.60');
insert into car (make, model, price) values ('Scion', 'FR-S', '65397.04');
insert into car (make, model, price) values ('Kia', 'Sportage', '82721.63');
insert into car (make, model, price) values ('Toyota', 'MR2', '53709.04');
insert into car (make, model, price) values ('Kia', 'Rio', '58445.29');
insert into car (make, model, price) values ('Jensen', 'Interceptor', '56355.60');
insert into car (make, model, price) values ('Dodge', 'Caravan', '80851.02');
insert into car (make, model, price) values ('Ford', 'E-Series', '79977.77');
insert into car (make, model, price) values ('Audi', '80', '65716.46');
insert into car (make, model, price) values ('Mercury', 'Topaz', '60538.08');
insert into car (make, model, price) values ('Nissan', 'Xterra', '85682.08');
insert into car (make, model, price) values ('Chevrolet', '1500', '95558.12');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '68121.60');
insert into car (make, model, price) values ('Suzuki', 'Equator', '70943.68');
insert into car (make, model, price) values ('Mazda', 'RX-7', '95230.41');
insert into car (make, model, price) values ('Maserati', 'Biturbo', '71496.33');
insert into car (make, model, price) values ('Cadillac', 'Escalade', '72755.68');
insert into car (make, model, price) values ('Jeep', 'Cherokee', '57280.69');
insert into car (make, model, price) values ('Ford', 'Econoline E250', '59081.07');
insert into car (make, model, price) values ('Volvo', 'S60', '90919.51');
insert into car (make, model, price) values ('Mitsubishi', 'Mighty Max Macro', '84362.34');
insert into car (make, model, price) values ('Kia', 'Optima', '95171.81');
insert into car (make, model, price) values ('Mercedes-Benz', 'CLS-Class', '76233.22');
insert into car (make, model, price) values ('Dodge', 'Ram Van 1500', '69418.47');
insert into car (make, model, price) values ('Pontiac', 'Grand Am', '76465.51');
insert into car (make, model, price) values ('BMW', 'X5', '67967.85');
insert into car (make, model, price) values ('Lexus', 'RX', '82788.94');
insert into car (make, model, price) values ('BMW', 'X3', '55781.44');
insert into car (make, model, price) values ('Maybach', '57', '73308.48');
insert into car (make, model, price) values ('Kia', 'Optima', '57137.14');
insert into car (make, model, price) values ('Porsche', 'Cayenne', '77779.51');
insert into car (make, model, price) values ('Mazda', 'B-Series', '71344.87');
insert into car (make, model, price) values ('Ford', 'Galaxie', '82365.64');
insert into car (make, model, price) values ('Oldsmobile', 'Ciera', '74670.61');
insert into car (make, model, price) values ('Ford', 'Expedition', '88342.39');
insert into car (make, model, price) values ('Land Rover', 'Range Rover Sport', '93696.95');
insert into car (make, model, price) values ('Chevrolet', 'Avalanche 1500', '79955.86');
insert into car (make, model, price) values ('Porsche', 'Panamera', '78341.09');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '87502.85');
insert into car (make, model, price) values ('Toyota', 'Land Cruiser', '89911.91');
insert into car (make, model, price) values ('Mitsubishi', 'Eclipse', '83628.51');
insert into car (make, model, price) values ('Chevrolet', 'Tahoe', '77541.83');
insert into car (make, model, price) values ('Ford', 'Five Hundred', '74567.94');
insert into car (make, model, price) values ('GMC', 'Yukon Denali', '97178.64');
insert into car (make, model, price) values ('Lotus', 'Evora', '97940.00');
insert into car (make, model, price) values ('GMC', 'Savana 1500', '70894.67');
insert into car (make, model, price) values ('Saturn', 'S-Series', '56430.24');
insert into car (make, model, price) values ('Mercedes-Benz', '500SEL', '74535.41');
insert into car (make, model, price) values ('Acura', 'RL', '77810.09');
insert into car (make, model, price) values ('Jeep', 'Wrangler', '87147.97');
insert into car (make, model, price) values ('Subaru', 'Forester', '72928.32');
insert into car (make, model, price) values ('Nissan', '370Z', '74546.94');
insert into car (make, model, price) values ('Ford', 'Explorer', '94577.87');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '77043.45');
insert into car (make, model, price) values ('BMW', 'M Roadster', '99853.12');
insert into car (make, model, price) values ('Toyota', 'Camry', '98317.85');
insert into car (make, model, price) values ('Lincoln', 'MKS', '80742.51');
insert into car (make, model, price) values ('Plymouth', 'Grand Voyager', '79648.75');
insert into car (make, model, price) values ('Chevrolet', 'Impala', '73492.46');
insert into car (make, model, price) values ('Plymouth', 'Acclaim', '92188.94');
insert into car (make, model, price) values ('Ford', 'Expedition', '54955.55');
insert into car (make, model, price) values ('BMW', 'M', '82651.07');
insert into car (make, model, price) values ('Maserati', 'GranTurismo', '89088.76');
insert into car (make, model, price) values ('Chevrolet', 'Blazer', '54397.98');
insert into car (make, model, price) values ('Porsche', '911', '64420.42');
insert into car (make, model, price) values ('Subaru', 'Loyale', '85471.89');
insert into car (make, model, price) values ('Chrysler', 'Crossfire', '81305.99');
insert into car (make, model, price) values ('Dodge', 'Stratus', '69034.73');
insert into car (make, model, price) values ('Honda', 'Passport', '81472.52');
insert into car (make, model, price) values ('Infiniti', 'G35', '91997.74');
insert into car (make, model, price) values ('Volkswagen', 'New Beetle', '55162.27');
insert into car (make, model, price) values ('Mitsubishi', 'Raider', '59214.03');
insert into car (make, model, price) values ('Mazda', '929', '72213.34');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '63709.77');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '52023.52');
insert into car (make, model, price) values ('Ford', 'Explorer', '90929.88');
insert into car (make, model, price) values ('GMC', 'Sonoma', '97070.92');
insert into car (make, model, price) values ('Lincoln', 'Continental', '97223.24');
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', '89930.63');
insert into car (make, model, price) values ('Buick', 'Century', '97014.61');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', '91074.72');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '52237.37');
insert into car (make, model, price) values ('Ford', 'F-Series', '91487.81');
insert into car (make, model, price) values ('Audi', 'Quattro', '69727.04');
insert into car (make, model, price) values ('Jeep', 'Liberty', '51308.33');
insert into car (make, model, price) values ('Mitsubishi', 'Pajero', '68968.76');
insert into car (make, model, price) values ('Mazda', 'Mazda5', '85267.46');
insert into car (make, model, price) values ('Buick', 'Skylark', '55760.64');
insert into car (make, model, price) values ('Jaguar', 'X-Type', '83191.08');
insert into car (make, model, price) values ('GMC', 'Vandura G2500', '90558.66');
insert into car (make, model, price) values ('Volvo', 'V70', '93356.32');
insert into car (make, model, price) values ('Mazda', 'MX-5', '66007.47');
insert into car (make, model, price) values ('Saab', '900', '66735.39');
insert into car (make, model, price) values ('Volkswagen', 'CC', '60088.67');
insert into car (make, model, price) values ('Dodge', 'Intrepid', '93851.70');
insert into car (make, model, price) values ('Chevrolet', 'Corvette', '64109.88');
insert into car (make, model, price) values ('Plymouth', 'Neon', '72866.73');
insert into car (make, model, price) values ('Honda', 'Pilot', '98204.89');
insert into car (make, model, price) values ('Chevrolet', 'Beretta', '72395.87');
insert into car (make, model, price) values ('Chevrolet', 'Express 3500', '87451.29');
insert into car (make, model, price) values ('Buick', 'Reatta', '74272.24');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '58777.36');
insert into car (make, model, price) values ('Chevrolet', 'Silverado', '92296.95');
insert into car (make, model, price) values ('Pontiac', '6000', '92181.00');
insert into car (make, model, price) values ('Volkswagen', 'Cabriolet', '94123.52');
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B150', '85933.56');
insert into car (make, model, price) values ('Ford', 'F-Series Super Duty', '97828.16');
insert into car (make, model, price) values ('Ford', 'Freestyle', '95422.93');
insert into car (make, model, price) values ('Ford', 'EXP', '83597.32');
insert into car (make, model, price) values ('Hyundai', 'Sonata', '85734.66');
insert into car (make, model, price) values ('GMC', 'Safari', '85141.81');
insert into car (make, model, price) values ('Suzuki', 'SJ', '54162.29');
insert into car (make, model, price) values ('Suzuki', 'Swift', '56336.23');
insert into car (make, model, price) values ('GMC', 'Sierra 2500', '67100.40');
insert into car (make, model, price) values ('Lincoln', 'Mark VIII', '91326.18');
insert into car (make, model, price) values ('Pontiac', '1000', '88591.89');
insert into car (make, model, price) values ('Subaru', 'Impreza', '57784.09');
insert into car (make, model, price) values ('Buick', 'Somerset', '54624.99');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '80129.20');
insert into car (make, model, price) values ('Chevrolet', 'G-Series G20', '56539.79');
insert into car (make, model, price) values ('Dodge', 'Ram Wagon B150', '88372.05');
insert into car (make, model, price) values ('Mercedes-Benz', 'S-Class', '87391.66');
insert into car (make, model, price) values ('Chevrolet', 'Classic', '61548.97');
insert into car (make, model, price) values ('Isuzu', 'Rodeo', '61598.87');
insert into car (make, model, price) values ('Mazda', 'RX-8', '83151.41');
insert into car (make, model, price) values ('Buick', 'LeSabre', '92889.38');
insert into car (make, model, price) values ('Infiniti', 'G35', '80867.09');
insert into car (make, model, price) values ('Cadillac', 'Allante', '57181.05');
insert into car (make, model, price) values ('Mitsubishi', 'Lancer Evolution', '88896.25');
insert into car (make, model, price) values ('Lotus', 'Exige', '98526.74');
insert into car (make, model, price) values ('Land Rover', 'LR4', '56519.65');
insert into car (make, model, price) values ('Mitsubishi', 'Galant', '59825.38');
insert into car (make, model, price) values ('Dodge', 'Dakota Club', '79450.06');
insert into car (make, model, price) values ('Lincoln', 'MKZ', '55894.31');
insert into car (make, model, price) values ('Cadillac', 'SRX', '50384.40');
insert into car (make, model, price) values ('Dodge', 'Magnum', '95844.61');
insert into car (make, model, price) values ('Ford', 'ZX2', '75919.68');
insert into car (make, model, price) values ('MINI', 'Cooper', '64374.77');
insert into car (make, model, price) values ('Plymouth', 'Voyager', '61572.12');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '80839.67');
insert into car (make, model, price) values ('Hyundai', 'Accent', '78450.20');
insert into car (make, model, price) values ('Ford', 'Econoline E350', '78258.73');
insert into car (make, model, price) values ('Honda', 'CR-X', '53885.94');
insert into car (make, model, price) values ('Mitsubishi', 'Montero Sport', '65207.89');
insert into car (make, model, price) values ('Acura', 'RL', '57322.94');
insert into car (make, model, price) values ('BMW', 'Z4 M', '96708.73');
insert into car (make, model, price) values ('GMC', 'Sonoma Club Coupe', '57119.17');
insert into car (make, model, price) values ('Nissan', 'Versa', '76295.99');
insert into car (make, model, price) values ('Toyota', 'Camry', '56834.55');
insert into car (make, model, price) values ('Lincoln', 'Continental', '77084.87');
insert into car (make, model, price) values ('Jaguar', 'XK', '66222.52');
insert into car (make, model, price) values ('Acura', 'Vigor', '87689.80');
insert into car (make, model, price) values ('Toyota', 'Avalon', '54515.53');
insert into car (make, model, price) values ('BMW', '7 Series', '88642.99');
insert into car (make, model, price) values ('Pontiac', 'Vibe', '58032.25');
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed6', '63251.19');
insert into car (make, model, price) values ('Volkswagen', 'Golf', '96888.25');
insert into car (make, model, price) values ('Eagle', 'Talon', '64324.28');
insert into car (make, model, price) values ('Mitsubishi', 'GTO', '99146.23');
insert into car (make, model, price) values ('Dodge', 'Ramcharger', '83408.89');
insert into car (make, model, price) values ('Acura', 'RDX', '66884.27');
insert into car (make, model, price) values ('Chrysler', 'Fifth Ave', '60185.66');
insert into car (make, model, price) values ('Maserati', 'Quattroporte', '83927.19');
insert into car (make, model, price) values ('BMW', 'X5', '60776.96');
insert into car (make, model, price) values ('Mercedes-Benz', 'C-Class', '63100.09');
insert into car (make, model, price) values ('Mazda', 'B-Series Plus', '56374.02');
insert into car (make, model, price) values ('Toyota', 'Highlander', '59035.31');
insert into car (make, model, price) values ('Ford', 'Mustang', '76322.35');
insert into car (make, model, price) values ('Chevrolet', 'Monte Carlo', '90816.57');
insert into car (make, model, price) values ('GMC', 'Sonoma', '85527.98');
insert into car (make, model, price) values ('Pontiac', 'Grand Prix', '85566.01');
insert into car (make, model, price) values ('Mazda', 'Miata MX-5', '73614.24');
insert into car (make, model, price) values ('Toyota', 'Tercel', '94487.42');
insert into car (make, model, price) values ('Chevrolet', 'S10', '70284.67');
insert into car (make, model, price) values ('Cadillac', 'XLR', '57959.49');
insert into car (make, model, price) values ('BMW', 'X5', '97755.10');
insert into car (make, model, price) values ('Subaru', 'SVX', '73259.40');
insert into car (make, model, price) values ('Geo', 'Prizm', '91817.75');
insert into car (make, model, price) values ('Kia', 'Borrego', '55094.91');
insert into car (make, model, price) values ('Chevrolet', 'HHR', '92456.14');
insert into car (make, model, price) values ('Mercury', 'Grand Marquis', '52163.55');
insert into car (make, model, price) values ('MINI', 'Countryman', '59522.80');
insert into car (make, model, price) values ('Toyota', '4Runner', '59019.26');
insert into car (make, model, price) values ('Jaguar', 'S-Type', '70764.43');
insert into car (make, model, price) values ('Chevrolet', 'Suburban 1500', '80903.11');
insert into car (make, model, price) values ('Ford', 'Ranger', '68898.67');
insert into car (make, model, price) values ('Ford', 'Freestar', '72712.31');
insert into car (make, model, price) values ('Lexus', 'LS', '60399.99');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '98615.50');
insert into car (make, model, price) values ('Honda', 'Civic', '51725.84');
insert into car (make, model, price) values ('Lincoln', 'Navigator L', '72354.89');
insert into car (make, model, price) values ('Buick', 'Electra', '50293.79');
insert into car (make, model, price) values ('Nissan', '240SX', '70948.20');
insert into car (make, model, price) values ('Ford', 'Freestyle', '69851.69');
insert into car (make, model, price) values ('Volkswagen', 'Passat', '64267.49');
insert into car (make, model, price) values ('Suzuki', 'Swift', '76932.34');
insert into car (make, model, price) values ('Mercury', 'Mariner', '91008.99');
insert into car (make, model, price) values ('Buick', 'Rendezvous', '66111.84');
insert into car (make, model, price) values ('Dodge', 'Ram Van 2500', '96524.68');
insert into car (make, model, price) values ('Pontiac', 'Firebird', '73787.73');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '55861.08');
insert into car (make, model, price) values ('Audi', '90', '88201.38');
insert into car (make, model, price) values ('Mazda', 'Mazdaspeed 3', '82366.30');
insert into car (make, model, price) values ('Mitsubishi', 'Truck', '72720.63');
insert into car (make, model, price) values ('Chrysler', 'Concorde', '82874.12');
insert into car (make, model, price) values ('Lincoln', 'LS', '75310.86');
insert into car (make, model, price) values ('Ford', 'Focus', '69678.33');
insert into car (make, model, price) values ('Volvo', 'S80', '84565.00');
insert into car (make, model, price) values ('Lexus', 'LX', '70190.35');
insert into car (make, model, price) values ('Land Rover', 'Range Rover', '56675.95');
insert into car (make, model, price) values ('Mazda', 'MPV', '98361.68');
insert into car (make, model, price) values ('Mazda', '626', '78226.16');
insert into car (make, model, price) values ('Chevrolet', 'Silverado 1500', '68003.82');
insert into car (make, model, price) values ('Volkswagen', 'Fox', '76163.66');
insert into car (make, model, price) values ('Cadillac', 'STS', '56448.39');
insert into car (make, model, price) values ('Infiniti', 'G', '86628.27');
insert into car (make, model, price) values ('Mazda', 'MPV', '77204.30');
insert into car (make, model, price) values ('Lotus', 'Esprit Turbo', '97094.71');
insert into car (make, model, price) values ('Spyker', 'C8', '89099.95');
insert into car (make, model, price) values ('Chevrolet', 'Astro', '53284.39');
insert into car (make, model, price) values ('Volkswagen', 'Corrado', '89157.40');
insert into car (make, model, price) values ('Pontiac', 'G6', '90564.57');
insert into car (make, model, price) values ('Austin', 'Mini Cooper', '77825.76');
insert into car (make, model, price) values ('Spyker', 'C8', '62013.15');
insert into car (make, model, price) values ('GMC', 'Envoy XL', '76600.02');
insert into car (make, model, price) values ('Hyundai', 'Accent', '82023.98');
insert into car (make, model, price) values ('Hyundai', 'Tucson', '85445.38');
insert into car (make, model, price) values ('Toyota', 'Avalon', '71406.15');
insert into car (make, model, price) values ('Dodge', 'Grand Caravan', '71917.66');
